### ISSUE TITLE
Clean tests are a great idea... may I have couple of questions?

### ISSUE THREAD

**Issue by simara-svatopluk** [ikvasnica/phpstan-clean-test#17]
Hi,
first of all - great job!

I don't understand why `setup` method is wrong.
If I have a test cases that works for example on `Cart` and `Extended Warranty`, while I'm testing a cart, and I want to have the `Extended Warranty` setup for each test same... Why not use the `setup` method where `$this->extendedWarranty` is filled in? Of course for each test case by the same setup.

I find useful to compare value objects by `assertEquals` because it is what I need. What is wrong with this approach?

**Comment by rask** [comment]
`setUp` spills state between test cases if you're not careful. In you case I would just add a getter in your testcase class, and use that to get a new  `Extended Warranty` instance for each test method (e.g. `protected function getExtendedWarrantyInstance()` or something).

Imagine your `setUp` has a `$this->thing instanceof Thing` that conditionally creates the `Thing`. In the meantime some test modifies the `Thing` by accident, and other test methods then rely on the modified thing. When you set up test order randomization you catch most of these edge cases, but rather there be no edge cases at all.

`assertEquals`, as you mentioned, is nice for value objects. Maybe consider adding a method for comparing two value objects, e.g. `$this->equals($that)` where `$this` and `$that` are instances of the same class?

I hope PHP adds operator overloading (is this the correct term?), meaning we could add a method like `isEqual($other, bool $strict = false) : bool` to an object that implements something like `Comparable` and PHP could then use that method when doing `==` and `===` in code. Or maybe some implementable marker interface that denotes value objects, which are then "loosely" compared between each other all the time.

In the end you can always disable certain rules to fit your workflow.

**Comment by ikvasnica** [comment]
@simara-svatopluk Hi, thank you very much!

Regarding the `setup` method - @rask has sum it up perfectly. I think creating a test setup should be responsibility of each test method. It increases readability, too. Also, it might happen that the object needs different setup for different test runs (i.e. you expect specific arguments to your mocked dependencies).

> I find useful to compare value objects by assertEquals because it is what I need. What is wrong with this approach?

That is totally okay! The rule forbids calling `assertEquals` only with scalar types. Arrays and objects will pass. 😉

**Comment by simara-svatopluk** [comment]
Thanks for answers.

Yes, the setup isn't that necessary, one line of code is sufficient in this case, and even more readable.

I find strange to have `equal ` method in production code that is used only in tests. But as You explained, it's used only for primitives, abs that makes sense!

So, great, everything makes sense, closing :rocket:

**Comment by rask** [comment]
@simara-svatopluk I'd say having an `equals` method in production might prove valuable, in terms of comparing things in general in your domain logic where a simple `==` or `===` does not suffice (e.g. value objects where there is a single field that can differ for instance). But yes, if it is written only to satisfy tests then it might be smelly.

**Comment by simara-svatopluk** [comment]
@rask value objects that have one field different are different value object. But You hit the point in the last sentence
> But yes, if it is written only to satisfy tests then it might be smelly.
