### ISSUE TITLE
StaticAssertOverThisAndStaticRule with Test-Extensions

### ISSUE THREAD

**Issue by temp** [ikvasnica/phpstan-clean-test#18]
Hi, I'm having a problem with the mentioned rule, since not all used assertions are coming from Phpunit Assert...

For example in functional tests in symfony, when using the WebTestCase, and for example the assertion assertResponseStatusCodeSame().

Maybe your Rule should check wether or not the method exists on Assert?

**Comment by ikvasnica** [comment]
Hi @temp , 
sorry for a late answer. 
Thank you for your feedback, I will check this one and try to fix it.

**Comment by ikvasnica** [comment]
Hi @temp ,
this should be fixed now in 0.3.1. Please, update and check.

Thank you again for creating the issue! 👍
