### ISSUE TITLE
Support for PHPStan v1

### ISSUE THREAD

**Issue by Wirone** [ikvasnica/phpstan-clean-test#20]
Hi, I've encountered this repository recently and it looks interesting 👏 . However, PHPStan `v0.*` is pretty outdated, so I'm asking for the v1 support 🙏 . We then might use this plugin in PHPCSFixer repo 🙂.

**Comment by ikvasnica** [comment]
Thanks for opening the issue, @Wirone, I will definitely look at it during the next week 🙂

**Comment by ikvasnica** [comment]
Hi @Wirone, I just released a new version v0.4 with support for PHP 8.1 and later + PHPStan 1.10 and later. I hope this will help.

If there is anything that is not working properly or if you need to support more versions, please let me know and I will try my best to fix it. :)

**Comment by Wirone** [comment]
Thank you very much! I'll try to implement it in Fixer in upcoming days 🙂.
